package com.gaspar.facturador.persistence.entity.enums;

public enum TipoPagoEnum {
    EFECTIVO(1, "EFECTIVO"),
    TARJETA(2, "TARJETA"),
    CHEQUE(3, "CHEQUE"),
    VALES(4, "VALES"),
    OTROS(5, "OTROS"),
    PAGO_POSTERIOR(6, "PAGO POSTERIOR"),
    TRANSFERENCIA_BANCARIA(7, "TRANSFERENCIA BANCARIA"),
    DEPOSITO_EN_CUENTA(8, "DEPOSITO EN CUENTA"),
    TRANSFERENCIA_SWIFT(9, "TRANSFERENCIA SWIFT"),
    GIFT_CARD(27, "GIFT-CARD"),
    CANAL_DE_PAGO(31, "CANAL DE PAGO"),
    BILLETERA_MOVIL(32, "BILLETERA MOVIL"),
    PAGO_ONLINE(33, "PAGO ONLINE"),
    DEBITO_AUTOMATICO(295, "DEBITO AUTOMATICO"),

    // Métodos combinados
    EFECTIVO_TARJETA(10, "EFECTIVO-TARJETA"),
    EFECTIVO_CHEQUE(11, "EFECTIVO-CHEQUE"),
    EFECTIVO_VALES(12, "EFECTIVO-VALES"),
    EFECTIVO_TRANSFERENCIA_BANCARIA(13, "EFECTIVO – TRANSFERENCIA BANCARIA"),
    EFECTIVO_DEPOSITO_EN_CUENTA(14, "EFECTIVO-DEPOSITO EN CUENTA"),
    EFECTIVO_TRANSFERENCIA_SWIFT(15, "EFECTIVO – TRANSFERENCIA BANCARIA SWIFT"),
    TARJETA_CHEQUE(16, "TARJETA-CHEQUE"),
    TARJETA_VALES(17, "TARJETA-VALES"),
    TARJETA_TRANSFERENCIA_BANCARIA(18, "TARJETA-TRANSFERENCIA BANCARIA"),
    TARJETA_DEPOSITO_EN_CUENTA(19, "TARJETA-DEPOSITO EN CUENTA"),
    TARJETA_TRANSFERENCIA_SWIFT(20, "TARJETA-TRANSFERENCIA SWIFT"),
    VALES_TRANSFERENCIA_BANCARIA(21, "VALES-TRANSFERENCIA BANCARIA"),
    VALES_DEPOSITO_EN_CUENTA(22, "VALES – DEPOSITO EN CUENTA"),
    VALES_SWIFT(23, "VALES – SWIFT"),
    TRANSFERENCIA_BANCARIA_DEPOSITO_EN_CUENTA(24, "TRANSFERENCIA BANCARIA-DEPOSITO EN CUENTA"),
    TRANSFERENCIA_BANCARIA_TRANSFERENCIA_SWIFT(25, "TRANSFERENCIA BANCARIA-TRANSFERENCIA SWIFT"),
    DEPOSITO_EN_CUENTA_TRANSFERENCIA_SWIFT(26, "DEPOSITO EN CUENTA – TRANSFERENCIA SWIFT"),
    OTROS_GIFT_CARD(30, "OTROS – GIFT CARD"),
    EFECTIVO_PAGO_POSTERIOR(830, "EFECTIVO – PAGO POSTERIOR"),
    EFECTIVO_GIFT_CARD(831, "EFECTIVO – GIFT CARD"),
    EFECTIVO_CANAL_PAGO(832, "EFECTIVO – CANAL PAGO"),
    EFECTIVO_BILLETERA_MOVIL(833, "EFECTIVO – BILLETERA MOVIL"),
    EFECTIVO_PAGO_ONLINE(834, "EFECTIVO – PAGO ONLINE"),
    TARJETA_PAGO_POSTERIOR(835, "TARJETA – PAGO POSTERIOR"),
    TARJETA_GIFT(836, "TARJETA – GIFT"),
    TARJETA_CANAL_PAGO(837, "TARJETA – CANAL PAGO"),
    TARJETA_BILLETERA_MOVIL(838, "TARJETA – BILLETERA MOVIL"),
    TARJETA_PAGO_ONLINE(839, "TARJETA – PAGO ONLINE"),
    CHEQUE_VALES(840, "CHEQUE – VALES"),
    CHEQUE_PAGO_POSTERIOR(841, "CHEQUE – PAGO POSTERIOR"),
    CHEQUE_TRANSFERENCIA_BANCARIA(842, "CHEQUE – TRANSFERENCIA BANCARIA"),
    CHEQUE_DEPOSITO_EN_CUENTA(843, "CHEQUE – DEPOSITO EN CUENTA"),
    CHEQUE_SWIFT(844, "CHEQUE – SWIFT"),
    CHEQUE_GIFT(845, "CHEQUE – GIFT"),
    CHEQUE_CANAL_PAGO(846, "CHEQUE – CANAL PAGO"),
    CHEQUE_BILLETERA(847, "CHEQUE – BILLETERA"),
    CHEQUE_PAGO_ONLINE(848, "CHEQUE – PAGO ONLINE"),
    VALES_GIFT(849, "VALES – GIFT"),
    VALES_CANAL_DE_PAGO(850, "VALES – CANAL DE PAGO"),
    VALES_BILLETERA_MOVIL(851, "VALES – BILLETERA MOVIL"),
    VALES_PAGO_ONLINE(852, "VALES – PAGO ONLINE"),
    PAGO_POSTERIOR_TRANSFERENCIA_BANCARIA(853, "PAGO POSTERIOR – TRANSFERENCIA BANCARIA"),
    PAGO_POSTERIOR_DEPOSITO_EN_CUENTA(854, "PAGO POSTERIOR – DEPOSITO EN CUENTA"),
    PAGO_POSTERIOR_SWIFT(855, "PAGO POSTERIOR – SWIFT"),
    PAGO_POSTERIOR_GIFT(856, "PAGO POSTERIOR – GIFT"),
    PAGO_POSTERIOR_CANAL(857, "PAGO POSTERIOR – CANAL"),
    PAGO_POSTERIOR_BILLETERA(858, "PAGO POSTERIOR – BILLETERA"),
    PAGO_POSTERIOR_PAGO_ONLINE(859, "PAGO POSTERIOR – PAGO ONLINE"),
    TRANSFERENCIA_BANCARIA_GIFT_CARD(861, "TRANSFERENCIA BANCARIA – GIFT-CARD"),
    TRANSFERENCIA_BANCARIA_CANAL_DE_PAGO(863, "TRANSFERENCIA BANCARIA – CANAL DE PAGO"),
    TRANSFERENCIA_BANCARIA_BILLETERA_MOVIL(866, "TRANSFERENCIA BANCARIA – BILLETERA MOVIL"),
    TRANSFERENCIA_BANCARIA_PAGO_ONLINE(867, "TRANSFERENCIA BANCARIA – PAGO ONLINE"),
    DEPOSITO_EN_CUENTA_GIFT_CARD(869, "DEPOSITO EN CUENTA – GIFT-CARD"),
    DEPOSITO_EN_CUENTA_CANAL_DE_PAGO(870, "DEPOSITO EN CUENTA – CANAL DE PAGO"),
    DEPOSITO_EN_CUENTA_BILLETERA_MOVIL(871, "DEPOSITO EN CUENTA – BILLETERA MOVIL"),
    DEPOSITO_EN_CUENTA_PAGO_ONLINE(872, "DEPOSITO EN CUENTA  – PAGO ONLINE"),
    SWIFT_GIFT(873, "SWIFT – GIFT"),
    SWIFT_CANAL_DE_PAGO(874, "SWIFT – CANAL DE PAGO"),
    SWIFT_BILLETERA_MOVIL(875, "SWIFT – BILLETERA MOVIL"),
    SWIFT_PAGO_ONLINE(876, "SWIFT – PAGO ONLINE"),
    GIFT_CARD_CANAL_DE_PAGO(877, "GIFT-CARD – CANAL DE PAGO"),
    GIFT_CARD_BILLETERA_MOVIL(878, "GIFT CARD – BILLETERA MOVIL"),
    GIFT_PAGO_ONLINE(879, "GIFT – PAGO ONLINE"),
    CANAL_DE_PAGO_BILLETERA_MOVIL(880, "CANAL DE PAGO – BILLETERA MOVIL"),
    CANAL_DE_PAGO_PAGO_ONLINE(881, "CANAL DE PAGO – PAGO ONLINE"),
    BILLETERA_MOVIL_PAGO_ONLINE(882, "BILLETERA MOVIL – PAGO ONLINE"),
    DEBITO_AUTOMATICO_EFECTIVO(1097, "DEBITO AUTOMATICO – EFECTIVO"),
    DEBITO_AUTOMATICO_TARJETA(1098, "DEBITO AUTOMATICO -TARJETA"),
    DEBITO_AUTOMATICO_CHEQUE(1099, "DEBITO AUTOMATICO – CHEQUE");

    private final int id;
    private final String descripcion;

    TipoPagoEnum(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }

    public int getId() {
        return id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public static TipoPagoEnum fromId(int id) {
        for (TipoPagoEnum tipo : TipoPagoEnum.values()) {
            if (tipo.getId() == id) {
                return tipo;
            }
        }
        throw new IllegalArgumentException("No existe un TipoPagoEnum con id " + id);
    }
}