version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: facturador
      POSTGRES_USER: inpasep
      POSTGRES_PASSWORD: inpasep1softcraft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/facturador
      SPRING_DATASOURCE_USERNAME: inpasep
      SPRING_DATASOURCE_PASSWORD: inpasep1softcraft
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: