services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: facturador
      POSTGRES_USER: gaspar
      POSTGRES_PASSWORD: armando1gaspar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/facturador
      SPRING_DATASOURCE_USERNAME: gaspar
      SPRING_DATASOURCE_PASSWORD: armando1gaspar
    ports:
      - "8080:8080"

volumes:
  postgres_data:
